### ISSUE TITLE
Cannot connect to host https:443

### ISSUE THREAD

**Issue by trosos** [rbw/snow#66]
Example in the file create-update-delete.py suggests instantiating `snow.Application` like
```python
app = Application(
    dict(
        address="https://<instance_name>.service-now.com",
        basic_auth=("<username>", "<password>")
    )
)
```

However, in my environment this fails with
```
snow.exceptions.ClientConnectionError: Cannot connect to host https:443 ssl:default [Name or service not known]
```
when awaiting on `r.create`.

To fix this, I needed to change the code not to contain the https url scheme:
```python
app = Application(
    dict(
        address="<instance_name>.service-now.com",
        basic_auth=("<username>", "<password>")
    )
)
```

I may look deeper into this if needed.

**Comment by rbw** [comment]
This was changed after `use_ssl` and `verify_ssl` was introduced. If `use_ssl` is set to false, the *http* scheme is prepended to `address`, otherwise *https*. I realize now that I haven't updated the examples to reflect this.

Perhaps the old format of scheme + authority (host+port) would be clearer? What do you think?

**Comment by trosos** [comment]
I have no strict opinion on this.

(Except that partial (zero-path without explicit slash) URIs like `http://example.com` look awkward to me; so personally, I like the current solution more and vote for updating of the examples.)
